name: food_recipe_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  #splash 
  another_flutter_splash_screen: ^1.2.0
  #lottie
  lottie: ^2.4.0
  #indicator
  pie_chart: ^5.4.0
  #text
  expandable_text: ^2.3.0


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  
  assets:
    - images/
    - images/lottie/
 

